# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  loaders:
    flysystem_loader:
      flysystem:
        filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
  data_loader: flysystem_loader

  filter_sets:
    squared_thumbnail_small:
      filters:
        thumbnail:
          size: [200, 200]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_medium:
      filters:
        thumbnail:
          size: [500, 500]
          mode: outbound
          allow_upscale: true
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
