# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    # default_adapter:
    #   local:
    #     directory: "%kernel.cache_dir%/flysystem"
    public_uploads_adapter:
      local:
        directory: "%kernel.project_dir%/public/uploads"
  filesystems:
    # default_filesystem:
    #   adapter: default_adapter
    #   alias: League\Flysystem\Filesystem
    public_uploads_filesystem:
      adapter: public_uploads_adapter
    #   alias: League\Flysystem\Filesystem
